Fixes recommended by the Unity Package Validation Suite (#71)
**Results:**

```
Validation Suite Results for package "com.candycoded.candycoded"
 - Path: /Users/scottdoxey/git/github/CandyCoded/Assets/Plugins/CandyCoded
 - Version: 1.1.2
 - Test Time: 1/26/2019 9:43:50 PM

VALIDATION RESULTS:
-------------------

Failed - "Documentation Validation"
Error: Please rename your "Documentation" folder to "Documentation~" so that its files are ignored by the asset database.

Failed - "Manifest Validation"
Error: In package.json, "name" needs to start with "com.unity.", and end with your package name.

Skipping Git tags check as this is a package in development.

Succeeded - "Assembly Definition Validation"
Checking: {Package-Root}/CandyCoded.asmdef

Checking: {Package-Root}/Tests/CandyCoded.EditorTests.asmdef

Succeeded - "ChangeLog Validation"

Succeeded - "Dependency Validation"

Succeeded - "Meta Files Validation"

Succeeded - "Required File Type Validation"

Succeeded - "Restricted File Type Validation"

Succeeded - "Tests Validation"

Succeeded - "Unity Version Validation"

Succeeded - "Package Update Validation"
Warning: This package is not a preview version, but it's the first version of the package.  Should this package version be tagged as 1.1.2-preview?

NotRun - "API Validation"
No previous package version. Skipping Semantic Versioning checks.

NotRun - "Package Diff Evaluation"
No previous package version. Skipping diff evaluation.

NotRun - "Project Template Validation"
com.candycoded.candycoded is not a project template.

NotRun - "Samples Validation"
No samples found. Skipping Samples Validation.

NotImplementedYet - "Folder Structure Validation"

NotImplementedYet - "License Validation"

NotImplementedYet - "Signature Validation"
```